=== lmazure/Homepage/css/schema.xsd
<?xml version="1.0" encoding="ISO-8859-1"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

<!-- Import xml: namespace -->
<xs:import namespace="http://www.w3.org/XML/1998/namespace" schemaLocation="xml.xsd"/>

<!-- definition of the types -->
<xs:simpleType name="noZeroInteger">
  <xs:restriction base="xs:integer">
    <xs:pattern value="[1-9]*[0-9]"/>
  </xs:restriction>
</xs:simpleType>

<xs:complexType name="person">
  <xs:sequence>
    <xs:element name="NAMEPREFIX" type="xs:string" minOccurs="0" maxOccurs="1"/>
    <xs:element name="FIRSTNAME" type="xs:string" minOccurs="0" maxOccurs="1"/>
    <xs:element name="MIDDLENAME" type="xs:string" minOccurs="0" maxOccurs="1"/>
    <xs:element name="LASTNAME" type="xs:string" minOccurs="0" maxOccurs="1"/>
    <xs:element name="NAMESUFFIX" type="xs:string" minOccurs="0" maxOccurs="1"/>
    <xs:element name="GIVENNAME" type="xs:string" minOccurs="0" maxOccurs="1"/>
  </xs:sequence>
</xs:complexType>

<xs:complexType name="fullDate">
  <xs:sequence>
    <xs:element name="YEAR" type="xs:integer"/>
    <xs:element name="MONTH">
      <xs:simpleType>
        <xs:restriction base="noZeroInteger">
          <xs:maxInclusive value="12"/>
        </xs:restriction>
      </xs:simpleType>
    </xs:element>
    <xs:element name="DAY">
      <xs:simpleType>
        <xs:restriction base="noZeroInteger">
          <xs:maxInclusive value="31"/>
        </xs:restriction>
      </xs:simpleType>
    </xs:element>
  </xs:sequence>
</xs:complexType>

<xs:complexType name="partialDate">
  <xs:sequence>
    <xs:element name="YEAR" type="xs:integer"/>
    <xs:element name="MONTH" minOccurs="0" maxOccurs="1">
      <xs:simpleType>
        <xs:restriction base="noZeroInteger">
          <xs:maxInclusive value="12"/>
        </xs:restriction>
      </xs:simpleType>
    </xs:element>
    <xs:element name="DAY" minOccurs="0" maxOccurs="1">
      <xs:simpleType>
        <xs:restriction base="noZeroInteger">
          <xs:maxInclusive value="31"/>
        </xs:restriction>
      </xs:simpleType>
    </xs:element>
  </xs:sequence>
</xs:complexType>

<xs:complexType name="duration">
  <xs:sequence>
    <xs:element name="HOUR" minOccurs="0" maxOccurs="1">
      <xs:simpleType>
        <xs:restriction base="noZeroInteger">
          <xs:minInclusive value="1"/>
        </xs:restriction>
      </xs:simpleType>
    </xs:element>
    <xs:element name="MINUTE" minOccurs="0" maxOccurs="1">
      <xs:simpleType>
        <xs:restriction base="noZeroInteger">
          <xs:maxInclusive value="59"/>
        </xs:restriction>
      </xs:simpleType>
    </xs:element>
    <xs:element name="SECOND" minOccurs="1" maxOccurs="1">
      <xs:simpleType>
        <xs:restriction base="noZeroInteger">
          <xs:maxInclusive value="59"/>
        </xs:restriction>
      </xs:simpleType>
    </xs:element>
  </xs:sequence>
</xs:complexType>

<xs:complexType name="content" mixed="true">
  <xs:choice minOccurs="0" maxOccurs="unbounded">
    <xs:element ref="BLIST"/>
    <xs:element ref="SLIST"/>
    <xs:element ref="NLIST"/>
    <xs:element ref="CLIST"/>
    <xs:element ref="LLIST"/>
    <xs:element ref="DEFINITIONTABLE"/>
    <xs:element ref="DEFINITION2TABLE"/>
    <xs:element ref="TABLE"/>
    <xs:element ref="MATH"/>
    <xs:element ref="MERMAID"/>
    <xs:element ref="TEXTBLOCK"/>
    <xs:element ref="CODEMENU"/>
    <xs:element ref="CODESAMPLE"/>
    <xs:element ref="CODEROUTINE"/>
    <xs:element ref="CODEFILENAME"/>
    <xs:element name="DATE" type="partialDate"/>
    <xs:element name="DURATION" type="duration"/>
    <xs:element ref="LINE"/>
    <xs:element ref="ANCHOR"/>
    <xs:element ref="U"/>
    <xs:element ref="B"/>
    <xs:element ref="I"/>
    <xs:element ref="SMALL"/>
    <xs:element ref="SUB"/>
    <xs:element ref="SUP"/>
    <xs:element ref="X"/>
    <xs:element ref="ARTICLE"/>
    <xs:element ref="BR"/>
    <xs:element ref="KEY"/>
    <xs:element ref="MODIFIERKEY"/>
    <xs:element ref="IMAGE"/>
    <xs:element name="AUTHOR" type="person"/>
    <xs:element name="KEYWORD"/>
  </xs:choice>
  <xs:attribute ref="xml:lang" use="optional"/>
</xs:complexType>

<!-- definition of the tags -->

<xs:element name="PAGE">
  <xs:complexType>
    <xs:sequence>
      <xs:element name="TITLE" type="xs:string" minOccurs="1" maxOccurs="1"/>
      <xs:element name="PATH" type="xs:string" minOccurs="1" maxOccurs="1"/>
      <xs:element name="DATE" type="fullDate" minOccurs="1" maxOccurs="1"/>
      <xs:element ref="CONTENT" minOccurs="1" maxOccurs="1"/>
      <xs:element ref="X" minOccurs="0" maxOccurs="unbounded"/>
      <xs:element ref="SCRIPT" minOccurs="0" maxOccurs="1"/>
    </xs:sequence>
    <xs:attribute name="special">
     <xs:simpleType>
       <xs:restriction base="xs:string">
         <xs:pattern value="indexed"/>
       </xs:restriction>
      </xs:simpleType>
    </xs:attribute>
    <xs:attribute name="status">
     <xs:simpleType>
       <xs:restriction base="xs:string">
         <xs:pattern value="unmaintained"/>
       </xs:restriction>
      </xs:simpleType>
    </xs:attribute>
    <xs:attribute ref="xml:lang" use="required"/>
  </xs:complexType>
</xs:element>

<xs:element name="CONTENT" type="content"/>

<xs:complexType name="List">
  <xs:sequence>
    <xs:element name="TITLE" type="content" minOccurs="0" maxOccurs="1"/>
    <xs:element name="SUBTITLE" type="content" minOccurs="0" maxOccurs="1"/>
    <xs:element name="ITEM" type="content" minOccurs="1" maxOccurs="unbounded"/>
  </xs:sequence>
</xs:complexType>

<xs:element name="BLIST" type="List"/>
<xs:element name="SLIST" type="List"/>
<xs:element name="NLIST" type="List"/>
<xs:element name="CLIST" type="List"/>
<xs:element name="LLIST" type="List"/>

<xs:element name="U" type="content"/>

<xs:element name="B" type="content"/>

<xs:element name="I" type="content"/>

<xs:element name="SMALL" type="content"/>

<xs:element name="SUB" type="xs:string"/>

<xs:element name="SUP" type="xs:string"/>

<xs:element name="X">
  <xs:complexType>
    <xs:sequence>
      <xs:element name="T" minOccurs="1" maxOccurs="1">
        <xs:complexType mixed="true">
          <xs:choice minOccurs="0" maxOccurs="unbounded">
            <xs:element ref="CODEROUTINE"/>
            <xs:element ref="CODEFILENAME"/>
          </xs:choice>
        </xs:complexType>
      </xs:element>
      <xs:element name="ATTRIBUTE" minOccurs="0" maxOccurs="unbounded">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="ATTRIBUTENAME" type="xs:string"/>
            <xs:element name="ATTRIBUTEVALUE" type="xs:string"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element name="ST" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
      <xs:element name="A" type="xs:anyURI" minOccurs="1" maxOccurs="1"/>
      <xs:element name="L" minOccurs="1" maxOccurs="3">
        <xs:simpleType>
         <xs:restriction base="xs:string">
           <xs:pattern value="de|en|fr|ru"/>
         </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="F" minOccurs="1" maxOccurs="unbounded">
        <xs:simpleType>
         <xs:restriction base="xs:string">
           <xs:pattern value="Flash|Flash Video|HTML|MP3|MP4|PDF|PostScript|PowerPoint|RealMedia|txt|Windows Media Player|Word"/>
         </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="FEED" minOccurs="0" maxOccurs="1">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="A" type="xs:anyURI"/>
            <xs:element name="F">
              <xs:simpleType>
               <xs:restriction base="xs:string">
                 <xs:pattern value="RSS|RSS2|Atom"/>
               </xs:restriction>
              </xs:simpleType>
            </xs:element>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element name="DURATION" type="duration" minOccurs="0" maxOccurs="1"/>
      <xs:element name="DATE" type="partialDate" minOccurs="0" maxOccurs="1"/>
    </xs:sequence>
    <xs:attribute name="status">
     <xs:simpleType>
       <xs:restriction base="xs:string">
         <xs:pattern value="obsolete|dead|zombie|removed"/>
       </xs:restriction>
      </xs:simpleType>
    </xs:attribute>
    <xs:attribute name="protection">
     <xs:simpleType>
       <xs:restriction base="xs:string">
         <xs:pattern value="payed_registration|free_registration"/>
       </xs:restriction>
      </xs:simpleType>
    </xs:attribute>
    <xs:attribute name="quality">
     <xs:simpleType>
       <xs:restriction base="xs:integer">
          <xs:minInclusive value="-2"/>
          <xs:maxInclusive value="2"/>
       </xs:restriction>
      </xs:simpleType>
    </xs:attribute>
  </xs:complexType>
</xs:element>

<xs:element name="ARTICLE">
  <xs:complexType>
    <xs:sequence>
      <xs:element ref="X" minOccurs="1" maxOccurs="unbounded"/>
      <xs:element name="AUTHOR" minOccurs="0" maxOccurs="unbounded" type="person"/>
      <xs:element name="DATE" type="partialDate" minOccurs="0" maxOccurs="1"/>
      <xs:element name="COMMENT" type="content" minOccurs="1" maxOccurs="1"/>
    </xs:sequence>
    <xs:attribute name="predecessor" type="xs:string"/>
  </xs:complexType>
</xs:element>

<xs:element name="KEYWORD">
  <xs:complexType>
    <xs:sequence>
      <xs:element name="KEYID" type="xs:string" minOccurs="1" maxOccurs="1"/>
      <xs:element name="KEYEDTEXT" type="content" minOccurs="1" maxOccurs="1"/>
    </xs:sequence>
  </xs:complexType>
</xs:element>

<xs:element name="LINE"/>

<xs:element name="ANCHOR" type="xs:string"/>

<xs:element name="DEFINITIONTABLE">
  <xs:complexType>
    <xs:sequence>
      <xs:element name="ROW" minOccurs="1" maxOccurs="unbounded">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="TERM" type="content"/>
            <xs:element name="DESC" type="content"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
</xs:element>

<xs:element name="DEFINITION2TABLE">
  <xs:complexType>
    <xs:sequence>
      <xs:element name="ROW" minOccurs="1" maxOccurs="unbounded">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="TERM1" type="content"/>
            <xs:element name="TERM2" type="content"/>
            <xs:element name="DESC" type="content"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
</xs:element>

<xs:element name="TABLE">
  <xs:complexType>
    <xs:sequence>
      <xs:element name="ROW" minOccurs="1" maxOccurs="unbounded">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="CELL" minOccurs="1" maxOccurs="unbounded">
              <xs:complexType>
                <xs:complexContent>
                  <xs:extension base="content">
                    <xs:attribute name="width" type="xs:nonNegativeInteger"/>
                    <xs:attribute name="height" type="xs:nonNegativeInteger"/>
                  </xs:extension>
                </xs:complexContent>
              </xs:complexType>
            </xs:element>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
</xs:element>

<xs:element name="TEXTBLOCK" type="content"/>

<xs:element name="MATH" type="xs:string"/>

<xs:element name="MERMAID" type="xs:string"/>

<xs:element name="CODEMENU">
  <xs:complexType mixed="true">
    <xs:sequence>
      <xs:element ref="CODEMENU" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>
</xs:element>

<xs:element name="CODESAMPLE">
  <xs:complexType mixed="true">
    <xs:sequence maxOccurs="unbounded">
      <xs:element ref="PROMPT" minOccurs="0"/>
      <xs:element ref="TAB" minOccurs="0" maxOccurs="unbounded"/>
      <xs:element ref="BR" minOccurs="0" maxOccurs="1"/>
      <xs:element name="I" minOccurs="0" maxOccurs="unbounded" type="xs:string"/>
      <xs:element name="B" minOccurs="0" maxOccurs="unbounded" type="xs:string"/>
      <xs:element name="U" minOccurs="0" maxOccurs="unbounded" type="xs:string"/>
      <xs:element ref="X" minOccurs="0" maxOccurs="unbounded"/>
      <xs:element ref="CODEFILENAME" minOccurs="0" maxOccurs="unbounded"/>
    </xs:sequence>
  <xs:attribute  name="language" use="optional"/>
  </xs:complexType>
</xs:element>

<xs:element name="CODEROUTINE">
  <xs:complexType mixed="true">
    <xs:sequence maxOccurs="unbounded">
      <xs:element name="I" minOccurs="0" maxOccurs="unbounded" type="xs:string"/>
      <xs:element ref="X" minOccurs="0" maxOccurs="unbounded"/>
      <xs:element ref="CODEFILENAME" minOccurs="0" maxOccurs="unbounded"/>
      <xs:element ref="TAB" minOccurs="0" maxOccurs="unbounded"/>
    </xs:sequence>
  </xs:complexType>
</xs:element>

<xs:element name="CODEFILENAME">
  <xs:complexType mixed="true">
    <xs:sequence minOccurs="0" maxOccurs="1">
      <xs:element ref="X" minOccurs="0" maxOccurs="1"/>
    </xs:sequence>
  </xs:complexType>
</xs:element>

<xs:element name="DATE" type="fullDate"/>

<xs:element name="PROMPT"/>

<xs:element name="TAB"/>

<xs:element name="BR"/>

<xs:element name="KEY">
  <xs:complexType>
    <xs:attribute name="id" type="xs:string"/>
  </xs:complexType>
</xs:element>

<xs:element name="MODIFIERKEY">
  <xs:complexType>
    <xs:attribute name="id" type="xs:string"/>
  </xs:complexType>
</xs:element>

<xs:element name="SCRIPT" type="xs:string"/>

<xs:element name="IMAGE" type="xs:anyURI"/>

</xs:schema>

=== lmazure/Homepage/notes/worddumpsc.xml
<?xml version="1.0"?>
<?xml-stylesheet type="text/xsl" href="../css/strict.xsl"?>
<PAGE xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../css/schema.xsd">
<TITLE>Dump of Word shortcuts</TITLE>
<PATH>notes/wordcust.xml</PATH>
<DATE><YEAR>2012</YEAR><MONTH>5</MONTH><DAY>14</DAY></DATE>
<CONTENT>

This is aimed mainly for a French azerty keyboard...

<CODESAMPLE> 
Option Explicit<BR/>
<BR/>
Private Sub DumpOneKey(key As Long, table As Variant)<BR/>
<BR/>
<TAB/>Dim bind As KeyBinding<BR/>
<TAB/>Dim rw As Variant<BR/>
<BR/>
<TAB/>Set rw = table.Rows.Add(beforeRow:=table.Rows(table.Rows.Count))<BR/>
<TAB/>Set bind = FindKey(BuildKeyCode(key))<BR/>
<TAB/>rw.Cells(1).Range.text = bind.KeyString<BR/>
<TAB/>rw.Cells(2).Range.text = bind.Command &amp; " " &amp; bind.CommandParameter<BR/>
<TAB/>Set bind = FindKey(BuildKeyCode(wdKeyShift, key))<BR/>
<TAB/>rw.Cells(3).Range.text = bind.Command &amp; " " &amp; bind.CommandParameter<BR/>
<TAB/>Set bind = FindKey(BuildKeyCode(wdKeyControl, key))<BR/>
<TAB/>rw.Cells(4).Range.text = bind.Command &amp; " " &amp; bind.CommandParameter<BR/>
<TAB/>Set bind = FindKey(BuildKeyCode(wdKeyControl, wdKeyShift, key))<BR/>
<TAB/>rw.Cells(5).Range.text = bind.Command &amp; " " &amp; bind.CommandParameter<BR/>
<TAB/>Set bind = FindKey(BuildKeyCode(wdKeyAlt, key))<BR/>
<TAB/>rw.Cells(6).Range.text = bind.Command &amp; " " &amp; bind.CommandParameter<BR/>
<TAB/>Set bind = FindKey(BuildKeyCode(wdKeyAlt, wdKeyShift, key))<BR/>
<TAB/>rw.Cells(7).Range.text = bind.Command &amp; " " &amp; bind.CommandParameter<BR/>
<TAB/>Set bind = FindKey(BuildKeyCode(wdKeyControl, wdKeyAlt, key))<BR/>
<TAB/>rw.Cells(8).Range.text = bind.Command &amp; " " &amp; bind.CommandParameter<BR/>
<TAB/>Set bind = FindKey(BuildKeyCode(wdKeyControl, wdKeyAlt, wdKeyShift, key))<BR/>
<TAB/>rw.Cells(9).Range.text = bind.Command &amp; " " &amp; bind.CommandParameter<BR/>
<TAB/>Set bind = FindKey(BuildKeyCode(wdKeyControl, wdKey1), BuildKeyCode(key))<BR/>
<TAB/>rw.Cells(10).Range.text = bind.Command &amp; " " &amp; bind.CommandParameter<BR/>
<TAB/>Set bind = FindKey(BuildKeyCode(wdKeyControl, wdKey1), BuildKeyCode(wdKeyShift, key))<BR/>
<TAB/>rw.Cells(11).Range.text = bind.Command &amp; " " &amp; bind.CommandParameter<BR/>
<TAB/>Set bind = FindKey(BuildKeyCode(wdKeyControl, wdKey2), BuildKeyCode(key))<BR/>
<TAB/>rw.Cells(12).Range.text = bind.Command &amp; " " &amp; bind.CommandParameter<BR/>
<TAB/>Set bind = FindKey(BuildKeyCode(wdKeyControl, wdKey2), BuildKeyCode(wdKeyShift, key))<BR/>
<TAB/>rw.Cells(13).Range.text = bind.Command &amp; " " &amp; bind.CommandParameter<BR/>
<TAB/>Set bind = FindKey(BuildKeyCode(wdKeyControl, wdKey4), BuildKeyCode(key))<BR/>
<TAB/>rw.Cells(14).Range.text = bind.Command &amp; " " &amp; bind.CommandParameter<BR/>
<TAB/>Set bind = FindKey(BuildKeyCode(wdKeyControl, wdKey4), BuildKeyCode(wdKeyShift, key))<BR/>
<TAB/>rw.Cells(15).Range.text = bind.Command &amp; " " &amp; bind.CommandParameter<BR/>
<TAB/>Set bind = FindKey(BuildKeyCode(wdKeyControl, wdKeyComma), BuildKeyCode(key))<BR/>
<TAB/>rw.Cells(16).Range.text = bind.Command &amp; " " &amp; bind.CommandParameter<BR/>
<TAB/>Set bind = FindKey(BuildKeyCode(wdKeyControl, wdKeyComma), BuildKeyCode(wdKeyShift, key))<BR/>
<TAB/>rw.Cells(17).Range.text = bind.Command &amp; " " &amp; bind.CommandParameter<BR/>
<TAB/>Set bind = FindKey(BuildKeyCode(wdKeyControl, wdKeySlash), BuildKeyCode(key))<BR/>
<TAB/>rw.Cells(18).Range.text = bind.Command &amp; " " &amp; bind.CommandParameter<BR/>
<TAB/>Set bind = FindKey(BuildKeyCode(wdKeyControl, wdKeySlash), BuildKeyCode(wdKeyShift, key))<BR/>
<TAB/>rw.Cells(19).Range.text = bind.Command &amp; " " &amp; bind.CommandParameter<BR/>
<TAB/>Set bind = FindKey(BuildKeyCode(wdKeyControl, wdKeyCloseSquareBrace), BuildKeyCode(key))<BR/>
<TAB/>rw.Cells(20).Range.text = bind.Command &amp; " " &amp; bind.CommandParameter<BR/>
<TAB/>Set bind = FindKey(BuildKeyCode(wdKeyControl, wdKeyCloseSquareBrace), BuildKeyCode(wdKeyShift, key))<BR/>
<TAB/>rw.Cells(21).Range.text = bind.Command &amp; " " &amp; bind.CommandParameter<BR/>
<BR/>
End Sub<BR/>
<BR/>
Sub DumpKeys()<BR/>
<BR/>
<TAB/>Dim newDoc As Variant<BR/>
<TAB/>Set newDoc = Documents.Add<BR/>
<BR/>
<TAB/>Dim table As Variant<BR/>
<TAB/>table = newDoc.Tables.Add(Range:=Selection.Range, NumRows:=2, NumColumns:=21)<BR/>
<TAB/>table.Rows(1).Cells(1).Range.text = "key"<BR/>
<TAB/>table.Rows(1).Cells(2).Range.text = ""<BR/>
<TAB/>table.Rows(1).Cells(3).Range.text = "Shift"<BR/>
<TAB/>table.Rows(1).Cells(4).Range.text = "Ctrl"<BR/>
<TAB/>table.Rows(1).Cells(5).Range.text = "Ctrl+Shift"<BR/>
<TAB/>table.Rows(1).Cells(6).Range.text = "Alt"<BR/>
<TAB/>table.Rows(1).Cells(7).Range.text = "Alt+Shift"<BR/>
<TAB/>table.Rows(1).Cells(8).Range.text = "Alt+Ctrl+"<BR/>
<TAB/>table.Rows(1).Cells(9).Range.text = "Alt+Ctrl+Shift"<BR/>
<TAB/>table.Rows(1).Cells(10).Range.text = "Ctrl+1"<BR/>
<TAB/>table.Rows(1).Cells(11).Range.text = "Ctrl+1 Shift"<BR/>
<TAB/>table.Rows(1).Cells(12).Range.text = "Ctrl+2"<BR/>
<TAB/>table.Rows(1).Cells(13).Range.text = "Ctrl+2 Shift"<BR/>
<TAB/>table.Rows(1).Cells(14).Range.text = "Ctrl+4"<BR/>
<TAB/>table.Rows(1).Cells(15).Range.text = "Ctrl+4 Shift"<BR/>
<TAB/>table.Rows(1).Cells(16).Range.text = "Ctrl+,"<BR/>
<TAB/>table.Rows(1).Cells(17).Range.text = "Ctrl+, Shift"<BR/>
<TAB/>table.Rows(1).Cells(18).Range.text = "Ctrl+:"<BR/>
<TAB/>table.Rows(1).Cells(19).Range.text = "Ctrl+: Shift"<BR/>
<TAB/>table.Rows(1).Cells(20).Range.text = "Ctrl+^"<BR/>
<TAB/>table.Rows(1).Cells(21).Range.text = "Ctrl+^ Shift"<BR/>
<BR/>
<TAB/>DumpOneKey wdKeyA, table<BR/>
<TAB/>DumpOneKey wdKeyB, table<BR/>
<TAB/>DumpOneKey wdKeyC, table<BR/>
<TAB/>DumpOneKey wdKeyD, table<BR/>
<TAB/>DumpOneKey wdKeyE, table<BR/>
<TAB/>DumpOneKey wdKeyF, table<BR/>
<TAB/>DumpOneKey wdKeyG, table<BR/>
<TAB/>DumpOneKey wdKeyH, table<BR/>
<TAB/>DumpOneKey wdKeyI, table<BR/>
<TAB/>DumpOneKey wdKeyJ, table<BR/>
<TAB/>DumpOneKey wdKeyK, table<BR/>
<TAB/>DumpOneKey wdKeyL, table<BR/>
<TAB/>DumpOneKey wdKeyM, table<BR/>
<TAB/>DumpOneKey wdKeyN, table<BR/>
<TAB/>DumpOneKey wdKeyO, table<BR/>
<TAB/>DumpOneKey wdKeyP, table<BR/>
<TAB/>DumpOneKey wdKeyQ, table<BR/>
<TAB/>DumpOneKey wdKeyR, table<BR/>
<TAB/>DumpOneKey wdKeyS, table<BR/>
<TAB/>DumpOneKey wdKeyT, table<BR/>
<TAB/>DumpOneKey wdKeyU, table<BR/>
<TAB/>DumpOneKey wdKeyV, table<BR/>
<TAB/>DumpOneKey wdKeyW, table<BR/>
<TAB/>DumpOneKey wdKeyX, table<BR/>
<TAB/>DumpOneKey wdKeyY, table<BR/>
<TAB/>DumpOneKey wdKeyZ, table<BR/>
<TAB/>DumpOneKey wdKey1, table<BR/>
<TAB/>DumpOneKey wdKey2, table<BR/>
<TAB/>DumpOneKey wdKey3, table<BR/>
<TAB/>DumpOneKey wdKey4, table<BR/>
<TAB/>DumpOneKey wdKey5, table<BR/>
<TAB/>DumpOneKey wdKey6, table<BR/>
<TAB/>DumpOneKey wdKey7, table<BR/>
<TAB/>DumpOneKey wdKey8, table<BR/>
<TAB/>DumpOneKey wdKey9, table<BR/>
<TAB/>DumpOneKey wdKey0, table<BR/>
<TAB/>DumpOneKey wdKeyF1, table<BR/>
<TAB/>DumpOneKey wdKeyF2, table<BR/>
<TAB/>DumpOneKey wdKeyF3, table<BR/>
<TAB/>DumpOneKey wdKeyF4, table<BR/>
<TAB/>DumpOneKey wdKeyF5, table<BR/>
<TAB/>DumpOneKey wdKeyF6, table<BR/>
<TAB/>DumpOneKey wdKeyF7, table<BR/>
<TAB/>DumpOneKey wdKeyF8, table<BR/>
<TAB/>DumpOneKey wdKeyF9, table<BR/>
<TAB/>DumpOneKey wdKeyF10, table<BR/>
<TAB/>DumpOneKey wdKeyF11, table<BR/>
<TAB/>DumpOneKey wdKeyF12, table<BR/>
<TAB/>DumpOneKey wdKeyPeriod, table<BR/>
<TAB/>DumpOneKey 223, table<BR/>
<TAB/>DumpOneKey wdKeySingleQuote, table<BR/>
<TAB/>DumpOneKey wdKeyOpenSquareBrace, table<BR/>
<TAB/>DumpOneKey wdKeyEquals, table<BR/>
<TAB/>DumpOneKey wdKeySemiColon, table<BR/>
<TAB/>DumpOneKey wdKeyBackSingleQuote, table<BR/>
<TAB/>DumpOneKey wdKeyBackSlash, table<BR/>
<TAB/>DumpOneKey wdKeyNumeric1, table<BR/>
<TAB/>DumpOneKey wdKeyNumeric2, table<BR/>
<TAB/>DumpOneKey wdKeyNumeric3, table<BR/>
<TAB/>DumpOneKey wdKeyNumeric4, table<BR/>
<TAB/>DumpOneKey wdKeyNumeric5, table<BR/>
<TAB/>DumpOneKey wdKeyNumeric6, table<BR/>
<TAB/>DumpOneKey wdKeyNumeric7, table<BR/>
<TAB/>DumpOneKey wdKeyNumeric8, table<BR/>
<TAB/>DumpOneKey wdKeyNumeric9, table<BR/>
<TAB/>DumpOneKey wdKeyNumeric0, table<BR/>
<TAB/>DumpOneKey wdKeyNumericDecimal, table<BR/>
<TAB/>DumpOneKey wdKeyNumericAdd, table<BR/>
<TAB/>DumpOneKey wdKeyNumericSubtract, table<BR/>
<TAB/>DumpOneKey wdKeyNumericMultiply, table<BR/>
<TAB/>DumpOneKey wdKeyNumericDivide, table<BR/>
<TAB/>DumpOneKey wdKeyInsert, table<BR/>
<TAB/>DumpOneKey wdKeyDelete, table<BR/>
<TAB/>DumpOneKey wdKeyHome, table<BR/>
<TAB/>DumpOneKey wdKeyEnd, table<BR/>
<TAB/>DumpOneKey wdKeyPageUp, table<BR/>
<TAB/>DumpOneKey wdKeyPageDown, table<BR/>
<TAB/>DumpOneKey wdKeyReturn, table<BR/>
<BR/>
<TAB/>table.Rows(table.Rows.Count).Delete<BR/>
End Sub
</CODESAMPLE>

</CONTENT>
</PAGE>

=== lmazure/Homepage/bouffe/0122.xml
<?xml version="1.0"?>
<?xml-stylesheet type="text/xsl" href="../css/strict.xsl"?>
<PAGE xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../css/schema.xsd" xml:lang="fr">
<TITLE>Nice crumble</TITLE>
<PATH>bouffe/0122.xml</PATH>
<DATE><YEAR>2010</YEAR><MONTH>10</MONTH><DAY>25</DAY></DATE>
<CONTENT>
<SLIST>
  <ITEM>40 min de préparation</ITEM>
  <ITEM>30 min de cuisson</ITEM>
  <ITEM>30 min pour la ratatouille</ITEM>
</SLIST>
<LINE/>
<BLIST>
  <ITEM>1 kg de tomates</ITEM>
  <ITEM>1 belle aubergine</ITEM>
  <ITEM>3 courgettes bien fermes</ITEM>
  <ITEM>1 poivron rouge et 1 poivron vert</ITEM>
  <ITEM>1 oignon</ITEM>
  <ITEM>1 gousse d'ail</ITEM>
  <ITEM>3 cuil. à soupe d'huile d'olive</ITEM>
  <ITEM>thym, romarin</ITEM>
  <ITEM>sel, poivre</ITEM>
</BLIST>
miettes
<BLIST>
  <ITEM>150g de farine</ITEM>
  <ITEM>100g de beurre</ITEM>
  <ITEM>40g de pignons</ITEM>
  <ITEM>60g de parmesan râpé</ITEM>
  <ITEM>sel</ITEM>
</BLIST>
<LINE/>
<BLIST>
  <ITEM>Emincez l'oignon et hacher très finement l'ail après en avoir ôté le germe. Faire chauffer l'huile dans une cocotte et y faire revenir l'ail et l'oignon.</ITEM>
  <ITEM>Couper l'aubergine en petits en petits cubes et les mettre dans la cocotte. Lorsqu'ils sont bien dorés, ajouter les poivrons coupés en lanières. Assaisonner avec le thym et le romarin, du sel et du poivre. Au bout de 20 minutes, ajouter les courgettes coupées en rondelles et les tomates pelées et épépinées. Bien mélanger et maintenir une cuisson assez vive pour que les légumes rendent leur eau.</ITEM>
  <ITEM>Pendant ce temps, préchauffez le four thermostat 6 (180°C) et confectionner les miettes : mélanger du bout des doigts la farine, le parmesan et le beurre. Ajouter les pignons.</ITEM>
  <ITEM>Versez la ratatouille dans un plat et répartir les miettes dessus. Laisser cuire dans le four chaud pendant 20 à 30 minutes.</ITEM>
  <ITEM>Servir juste chaud avec du chèvre frais ou de fines tranches de mozzarella.</ITEM>
</BLIST>
<I><U>source :</U> "Crumbles" par Camille Le Foll - page 54</I>
</CONTENT>
</PAGE>
