=== lmazure/Homepage/css/schema.xsd
<?xml version="1.0" encoding="ISO-8859-1"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

<!-- Import xml: namespace -->
<xs:import namespace="http://www.w3.org/XML/1998/namespace" schemaLocation="xml.xsd"/>

<!-- definition of the types -->
<xs:simpleType name="noZeroInteger">
  <xs:restriction base="xs:integer">
    <xs:pattern value="[1-9]*[0-9]"/>
  </xs:restriction>
</xs:simpleType>

<xs:complexType name="person">
  <xs:sequence>
    <xs:element name="NAMEPREFIX" type="xs:string" minOccurs="0" maxOccurs="1"/>
    <xs:element name="FIRSTNAME" type="xs:string" minOccurs="0" maxOccurs="1"/>
    <xs:element name="MIDDLENAME" type="xs:string" minOccurs="0" maxOccurs="1"/>
    <xs:element name="LASTNAME" type="xs:string" minOccurs="0" maxOccurs="1"/>
    <xs:element name="NAMESUFFIX" type="xs:string" minOccurs="0" maxOccurs="1"/>
    <xs:element name="GIVENNAME" type="xs:string" minOccurs="0" maxOccurs="1"/>
  </xs:sequence>
</xs:complexType>

<xs:complexType name="fullDate">
  <xs:sequence>
    <xs:element name="YEAR" type="xs:integer"/>
    <xs:element name="MONTH">
      <xs:simpleType>
        <xs:restriction base="noZeroInteger">
          <xs:maxInclusive value="12"/>
        </xs:restriction>
      </xs:simpleType>
    </xs:element>
    <xs:element name="DAY">
      <xs:simpleType>
        <xs:restriction base="noZeroInteger">
          <xs:maxInclusive value="31"/>
        </xs:restriction>
      </xs:simpleType>
    </xs:element>
  </xs:sequence>
</xs:complexType>

<xs:complexType name="partialDate">
  <xs:sequence>
    <xs:element name="YEAR" type="xs:integer"/>
    <xs:element name="MONTH" minOccurs="0" maxOccurs="1">
      <xs:simpleType>
        <xs:restriction base="noZeroInteger">
          <xs:maxInclusive value="12"/>
        </xs:restriction>
      </xs:simpleType>
    </xs:element>
    <xs:element name="DAY" minOccurs="0" maxOccurs="1">
      <xs:simpleType>
        <xs:restriction base="noZeroInteger">
          <xs:maxInclusive value="31"/>
        </xs:restriction>
      </xs:simpleType>
    </xs:element>
  </xs:sequence>
</xs:complexType>

<xs:complexType name="duration">
  <xs:sequence>
    <xs:element name="HOUR" minOccurs="0" maxOccurs="1">
      <xs:simpleType>
        <xs:restriction base="noZeroInteger">
          <xs:minInclusive value="1"/>
        </xs:restriction>
      </xs:simpleType>
    </xs:element>
    <xs:element name="MINUTE" minOccurs="0" maxOccurs="1">
      <xs:simpleType>
        <xs:restriction base="noZeroInteger">
          <xs:maxInclusive value="59"/>
        </xs:restriction>
      </xs:simpleType>
    </xs:element>
    <xs:element name="SECOND" minOccurs="1" maxOccurs="1">
      <xs:simpleType>
        <xs:restriction base="noZeroInteger">
          <xs:maxInclusive value="59"/>
        </xs:restriction>
      </xs:simpleType>
    </xs:element>
  </xs:sequence>
</xs:complexType>

<xs:complexType name="content" mixed="true">
  <xs:choice minOccurs="0" maxOccurs="unbounded">
    <xs:element ref="BLIST"/>
    <xs:element ref="SLIST"/>
    <xs:element ref="NLIST"/>
    <xs:element ref="CLIST"/>
    <xs:element ref="LLIST"/>
    <xs:element ref="DEFINITIONTABLE"/>
    <xs:element ref="DEFINITION2TABLE"/>
    <xs:element ref="TABLE"/>
    <xs:element ref="MATH"/>
    <xs:element ref="MERMAID"/>
    <xs:element ref="TEXTBLOCK"/>
    <xs:element ref="CODEMENU"/>
    <xs:element ref="CODESAMPLE"/>
    <xs:element ref="CODEROUTINE"/>
    <xs:element ref="CODEFILENAME"/>
    <xs:element name="DATE" type="partialDate"/>
    <xs:element name="DURATION" type="duration"/>
    <xs:element ref="LINE"/>
    <xs:element ref="ANCHOR"/>
    <xs:element ref="U"/>
    <xs:element ref="B"/>
    <xs:element ref="I"/>
    <xs:element ref="SMALL"/>
    <xs:element ref="SUB"/>
    <xs:element ref="SUP"/>
    <xs:element ref="X"/>
    <xs:element ref="ARTICLE"/>
    <xs:element ref="BR"/>
    <xs:element ref="KEY"/>
    <xs:element ref="MODIFIERKEY"/>
    <xs:element ref="IMAGE"/>
    <xs:element name="AUTHOR" type="person"/>
    <xs:element name="KEYWORD"/>
  </xs:choice>
  <xs:attribute ref="xml:lang" use="optional"/>
</xs:complexType>

<!-- definition of the tags -->

<xs:element name="PAGE">
  <xs:complexType>
    <xs:sequence>
      <xs:element name="TITLE" type="xs:string" minOccurs="1" maxOccurs="1"/>
      <xs:element name="PATH" type="xs:string" minOccurs="1" maxOccurs="1"/>
      <xs:element name="DATE" type="fullDate" minOccurs="1" maxOccurs="1"/>
      <xs:element ref="CONTENT" minOccurs="1" maxOccurs="1"/>
      <xs:element ref="X" minOccurs="0" maxOccurs="unbounded"/>
      <xs:element ref="SCRIPT" minOccurs="0" maxOccurs="1"/>
    </xs:sequence>
    <xs:attribute name="special">
     <xs:simpleType>
       <xs:restriction base="xs:string">
         <xs:pattern value="indexed"/>
       </xs:restriction>
      </xs:simpleType>
    </xs:attribute>
    <xs:attribute name="status">
     <xs:simpleType>
       <xs:restriction base="xs:string">
         <xs:pattern value="unmaintained"/>
       </xs:restriction>
      </xs:simpleType>
    </xs:attribute>
    <xs:attribute ref="xml:lang" use="required"/>
  </xs:complexType>
</xs:element>

<xs:element name="CONTENT" type="content"/>

<xs:complexType name="List">
  <xs:sequence>
    <xs:element name="TITLE" type="content" minOccurs="0" maxOccurs="1"/>
    <xs:element name="SUBTITLE" type="content" minOccurs="0" maxOccurs="1"/>
    <xs:element name="ITEM" type="content" minOccurs="1" maxOccurs="unbounded"/>
  </xs:sequence>
</xs:complexType>

<xs:element name="BLIST" type="List"/>
<xs:element name="SLIST" type="List"/>
<xs:element name="NLIST" type="List"/>
<xs:element name="CLIST" type="List"/>
<xs:element name="LLIST" type="List"/>

<xs:element name="U" type="content"/>

<xs:element name="B" type="content"/>

<xs:element name="I" type="content"/>

<xs:element name="SMALL" type="content"/>

<xs:element name="SUB" type="xs:string"/>

<xs:element name="SUP" type="xs:string"/>

<xs:element name="X">
  <xs:complexType>
    <xs:sequence>
      <xs:element name="T" minOccurs="1" maxOccurs="1">
        <xs:complexType mixed="true">
          <xs:choice minOccurs="0" maxOccurs="unbounded">
            <xs:element ref="CODEROUTINE"/>
            <xs:element ref="CODEFILENAME"/>
          </xs:choice>
        </xs:complexType>
      </xs:element>
      <xs:element name="ATTRIBUTE" minOccurs="0" maxOccurs="unbounded">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="ATTRIBUTENAME" type="xs:string"/>
            <xs:element name="ATTRIBUTEVALUE" type="xs:string"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element name="ST" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
      <xs:element name="A" type="xs:anyURI" minOccurs="1" maxOccurs="1"/>
      <xs:element name="L" minOccurs="1" maxOccurs="3">
        <xs:simpleType>
         <xs:restriction base="xs:string">
           <xs:pattern value="de|en|fr|ru"/>
         </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="F" minOccurs="1" maxOccurs="unbounded">
        <xs:simpleType>
         <xs:restriction base="xs:string">
           <xs:pattern value="Flash|Flash Video|HTML|MP3|MP4|PDF|PostScript|PowerPoint|RealMedia|txt|Windows Media Player|Word"/>
         </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="FEED" minOccurs="0" maxOccurs="1">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="A" type="xs:anyURI"/>
            <xs:element name="F">
              <xs:simpleType>
               <xs:restriction base="xs:string">
                 <xs:pattern value="RSS|RSS2|Atom"/>
               </xs:restriction>
              </xs:simpleType>
            </xs:element>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element name="DURATION" type="duration" minOccurs="0" maxOccurs="1"/>
      <xs:element name="DATE" type="partialDate" minOccurs="0" maxOccurs="1"/>
    </xs:sequence>
    <xs:attribute name="status">
     <xs:simpleType>
       <xs:restriction base="xs:string">
         <xs:pattern value="obsolete|dead|zombie|removed"/>
       </xs:restriction>
      </xs:simpleType>
    </xs:attribute>
    <xs:attribute name="protection">
     <xs:simpleType>
       <xs:restriction base="xs:string">
         <xs:pattern value="payed_registration|free_registration"/>
       </xs:restriction>
      </xs:simpleType>
    </xs:attribute>
    <xs:attribute name="quality">
     <xs:simpleType>
       <xs:restriction base="xs:integer">
          <xs:minInclusive value="-2"/>
          <xs:maxInclusive value="2"/>
       </xs:restriction>
      </xs:simpleType>
    </xs:attribute>
  </xs:complexType>
</xs:element>

<xs:element name="ARTICLE">
  <xs:complexType>
    <xs:sequence>
      <xs:element ref="X" minOccurs="1" maxOccurs="unbounded"/>
      <xs:element name="AUTHOR" minOccurs="0" maxOccurs="unbounded" type="person"/>
      <xs:element name="DATE" type="partialDate" minOccurs="0" maxOccurs="1"/>
      <xs:element name="COMMENT" type="content" minOccurs="1" maxOccurs="1"/>
    </xs:sequence>
    <xs:attribute name="predecessor" type="xs:string"/>
  </xs:complexType>
</xs:element>

<xs:element name="KEYWORD">
  <xs:complexType>
    <xs:sequence>
      <xs:element name="KEYID" type="xs:string" minOccurs="1" maxOccurs="1"/>
      <xs:element name="KEYEDTEXT" type="content" minOccurs="1" maxOccurs="1"/>
    </xs:sequence>
  </xs:complexType>
</xs:element>

<xs:element name="LINE"/>

<xs:element name="ANCHOR" type="xs:string"/>

<xs:element name="DEFINITIONTABLE">
  <xs:complexType>
    <xs:sequence>
      <xs:element name="ROW" minOccurs="1" maxOccurs="unbounded">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="TERM" type="content"/>
            <xs:element name="DESC" type="content"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
</xs:element>

<xs:element name="DEFINITION2TABLE">
  <xs:complexType>
    <xs:sequence>
      <xs:element name="ROW" minOccurs="1" maxOccurs="unbounded">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="TERM1" type="content"/>
            <xs:element name="TERM2" type="content"/>
            <xs:element name="DESC" type="content"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
</xs:element>

<xs:element name="TABLE">
  <xs:complexType>
    <xs:sequence>
      <xs:element name="ROW" minOccurs="1" maxOccurs="unbounded">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="CELL" minOccurs="1" maxOccurs="unbounded">
              <xs:complexType>
                <xs:complexContent>
                  <xs:extension base="content">
                    <xs:attribute name="width" type="xs:nonNegativeInteger"/>
                    <xs:attribute name="height" type="xs:nonNegativeInteger"/>
                  </xs:extension>
                </xs:complexContent>
              </xs:complexType>
            </xs:element>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
</xs:element>

<xs:element name="TEXTBLOCK" type="content"/>

<xs:element name="MATH" type="xs:string"/>

<xs:element name="MERMAID" type="xs:string"/>

<xs:element name="CODEMENU">
  <xs:complexType mixed="true">
    <xs:sequence>
      <xs:element ref="CODEMENU" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>
</xs:element>

<xs:element name="CODESAMPLE">
  <xs:complexType mixed="true">
    <xs:sequence maxOccurs="unbounded">
      <xs:element ref="PROMPT" minOccurs="0"/>
      <xs:element ref="TAB" minOccurs="0" maxOccurs="unbounded"/>
      <xs:element ref="BR" minOccurs="0" maxOccurs="1"/>
      <xs:element name="I" minOccurs="0" maxOccurs="unbounded" type="xs:string"/>
      <xs:element name="B" minOccurs="0" maxOccurs="unbounded" type="xs:string"/>
      <xs:element name="U" minOccurs="0" maxOccurs="unbounded" type="xs:string"/>
      <xs:element ref="X" minOccurs="0" maxOccurs="unbounded"/>
      <xs:element ref="CODEFILENAME" minOccurs="0" maxOccurs="unbounded"/>
    </xs:sequence>
  <xs:attribute  name="language" use="optional"/>
  </xs:complexType>
</xs:element>

<xs:element name="CODEROUTINE">
  <xs:complexType mixed="true">
    <xs:sequence maxOccurs="unbounded">
      <xs:element name="I" minOccurs="0" maxOccurs="unbounded" type="xs:string"/>
      <xs:element ref="X" minOccurs="0" maxOccurs="unbounded"/>
      <xs:element ref="CODEFILENAME" minOccurs="0" maxOccurs="unbounded"/>
      <xs:element ref="TAB" minOccurs="0" maxOccurs="unbounded"/>
    </xs:sequence>
  </xs:complexType>
</xs:element>

<xs:element name="CODEFILENAME">
  <xs:complexType mixed="true">
    <xs:sequence minOccurs="0" maxOccurs="1">
      <xs:element ref="X" minOccurs="0" maxOccurs="1"/>
    </xs:sequence>
  </xs:complexType>
</xs:element>

<xs:element name="DATE" type="fullDate"/>

<xs:element name="PROMPT"/>

<xs:element name="TAB"/>

<xs:element name="BR"/>

<xs:element name="KEY">
  <xs:complexType>
    <xs:attribute name="id" type="xs:string"/>
  </xs:complexType>
</xs:element>

<xs:element name="MODIFIERKEY">
  <xs:complexType>
    <xs:attribute name="id" type="xs:string"/>
  </xs:complexType>
</xs:element>

<xs:element name="SCRIPT" type="xs:string"/>

<xs:element name="IMAGE" type="xs:anyURI"/>

</xs:schema>

=== lmazure/Homepage/notes/javagenerics.xml
<?xml version="1.0"?>
<?xml-stylesheet type="text/xsl" href="../css/strict.xsl"?>
<PAGE xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../css/schema.xsd" xml:lang="en">
<TITLE>Java Generics</TITLE>
<PATH>notes/javagenerics.xml</PATH>
<DATE><YEAR>2018</YEAR><MONTH>5</MONTH><DAY>30</DAY></DATE>
<CONTENT>
Generic type declaration: <CODEROUTINE>public class Box&lt;T&gt;</CODEROUTINE>
<CODEROUTINE>T</CODEROUTINE> is a type variable or a formal type parameter
<CODESAMPLE language="java">public class Box&lt;T&gt; {

    private T t;

    public void add(T t) {
        this.t = t;
    }

    public T get() {
        return t;
    }
}</CODESAMPLE>
The class is used as: <CODEROUTINE>Box&lt;Integer&gt; integerBox = new Box&lt;Integer&gt;();</CODEROUTINE><BR/>
<BR/>
<BLIST><TITLE>The most commonly used type parameter names are</TITLE>
  <ITEM>E: Element (for a Collection)</ITEM>
  <ITEM>K: Key</ITEM>
  <ITEM>N: Number</ITEM>
  <ITEM>T: Type</ITEM>
  <ITEM>V: Value</ITEM>
  <ITEM>S,U,V…: 2nd, 3rd, 4th… types</ITEM>
</BLIST>
Type parameters can also be declared within method and constructor signatures to create generic methods and generic constructors.
<CODESAMPLE language="java">public static &lt;U&gt; void fillBoxes(U u, List&lt;Box&lt;U&gt;&gt; boxes) {
    for (Box&lt;U&gt; box : boxes) {
        box.add(u);
    }
}</CODESAMPLE>
The method is used as <CODEROUTINE>Box.fillBoxes(red, crayonBoxes);</CODEROUTINE>.<BR/>
This feature, known as type inference, allows you to invoke a generic method as you would an ordinary method, without specifying a type between angle brackets.<BR/>
<BR/>
<BLIST><TITLE><U><B>Bounded Type Parameters</B></U></TITLE>
  <ITEM>It is possible to restrict the kinds of types that are allowed to be passed to a type parameter. For example, a method that operates on numbers might only want to accept instances of <CODEROUTINE>Number</CODEROUTINE> or its subclasses. This is what bounded type parameters are for.<BR/>
    To declare a bounded type parameter, list the type parameter's name, followed by the <CODEROUTINE>extends</CODEROUTINE> keyword, followed by its upper bound. Note that, in this context, <CODEROUTINE>extends</CODEROUTINE> is used in a general sense to mean either "extends" (as in classes) or "implements" (as in interfaces).
    <CODESAMPLE language="java">public &lt;U extends Number&gt; void inspect(U u){
    …
}</CODESAMPLE></ITEM>
  <ITEM>To specify additional interfaces that must be implemented, use the &amp; character, as in: <CODEROUTINE>&lt;U extends Number &amp; MyInterface&gt;</CODEROUTINE>.</ITEM>
  <ITEM><CODESAMPLE language="java">public void boxTest(Box&lt;Number&gt; b){
    …
}</CODESAMPLE>
    will not accept a parameter of type <CODEROUTINE>Box&lt;Double&gt;</CODEROUTINE></ITEM>
  <ITEM><BLIST><TITLE>Wildcards</TITLE>
    <ITEM>Upper bound: <CODEROUTINE>&lt;? extends Animal&gt;</CODEROUTINE> means an unknown type that is a subtype of <CODEROUTINE>Animal</CODEROUTINE>, possibly <CODEROUTINE>Animal</CODEROUTINE> itself (covariance)</ITEM>
    <ITEM>Lower bound: <CODEROUTINE>&lt;? super Animal&gt;</CODEROUTINE> means an unknown type that is a supertype of <CODEROUTINE>Animal</CODEROUTINE>, possibly <CODEROUTINE>Animal</CODEROUTINE> itself (contravariance)</ITEM>
    <ITEM>Unbounded wildcard: <CODEROUTINE>&lt;?&gt;</CODEROUTINE>, this is the same as <CODEROUTINE>&lt;? extends Object&gt;</CODEROUTINE></ITEM>
    <ITEM>Use covariance when intend to take generic values out of a structure.<BR/>
      Use contravariance when intend to put generic values into a structure.<BR/>
      Use invariance when intend to do both.</ITEM>
  </BLIST></ITEM>
  <ITEM><CODESAMPLE language="java">public void boxTest(Box&lt;? extends Number&gt; b){
    …
}</CODESAMPLE>
    will accept a parameter of type <CODEROUTINE>Box&lt;Double&gt;</CODEROUTINE>.<BR/>
    Bounded type parameters limit the kinds of types that can be passed into a type parameter.</ITEM>
</BLIST>
<U><B>Type Erasure</B></U><BR/>
When a generic type is instantiated, the compiler translates those types by a technique called type erasure, a process where the compiler removes all information related to type parameters and type arguments within a class or method. Type erasure enables Java applications that use generics to maintain binary compatibility with Java libraries and applications that were created before generics.
For instance, <CODEROUTINE>Box&lt;String&gt;</CODEROUTINE> is translated to type <CODEROUTINE>Box</CODEROUTINE>, which is called the raw type, a raw type is a generic class or interface name without any type arguments. This means that you cannot find out what type of Object a generic class is using at runtime. The following operations are not possible:
<CODESAMPLE language="java">public class MyClass&lt;E&gt; {
    public static void myMethod(Object item) {
        if (item instanceof E) {  //Compiler error
            …
        }
        E item2 = new E();   //Compiler error
        E[] iArray = new E[10]; //Compiler error
        E obj = (E)new Object(); //Unchecked cast warning
    }
}</CODESAMPLE>
</CONTENT>
</PAGE>

=== lmazure/Homepage/links/mensi.xml
<?xml version="1.0"?>
<?xml-stylesheet type="text/xsl" href="../css/strict.xsl"?>
<PAGE status="unmaintained" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../css/schema.xsd" xml:lang="en">
<TITLE>MENSI</TITLE>
<PATH>links/mensi.xml</PATH>
<DATE><YEAR>2017</YEAR><MONTH>2</MONTH><DAY>8</DAY></DATE>
<CONTENT>
<BLIST><TITLE>Articles</TITLE>
<ITEM><ARTICLE><X protection="free_registration"><T>What Happened to That Bridge?</T><A>https://www.qualitydigest.com/inside/metrology-news/what-happened-bridge-080807.html</A><L>en</L><F>HTML</F></X><DATE><YEAR>2007</YEAR><MONTH>8</MONTH></DATE><COMMENT>Leica ScanStation is used for analysing a bridge collapse.</COMMENT></ARTICLE></ITEM>
</BLIST>
</CONTENT>
</PAGE>

=== lmazure/Homepage/links/house.xml
<?xml version="1.0"?>
<?xml-stylesheet type="text/xsl" href="../css/strict.xsl"?>
<PAGE xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../css/schema.xsd">
<TITLE>House</TITLE>
<PATH>links/house.xml</PATH>
<DATE><YEAR>2019</YEAR><MONTH>6</MONTH><DAY>10</DAY></DATE>
<CONTENT>
<BLIST>
  <ITEM><X><T>Demande de Valeur Foncière</T><A>https://app.dvf.etalab.gouv.fr</A><L>fr</L><F>HTML</F></X></ITEM>
  <ITEM><BLIST><TITLE>Real estate advertisements</TITLE>
    <ITEM><X><T>seloger.com</T><A>https://www.seloger.com/</A><L>fr</L><F>HTML</F></X></ITEM>
    <ITEM><X><T>paruvendu.fr</T><A>https://www.paruvendu.fr/</A><L>fr</L><F>HTML</F></X></ITEM>
    <ITEM><X><T>De Particulier A Particulier</T><A>https://www.pap.fr</A><L>fr</L><F>HTML</F></X></ITEM>
    <ITEM><X><T>a vendre a louer</T><A>https://www.avendrealouer.fr</A><L>fr</L><F>HTML</F></X></ITEM>
    <ITEM><X><T>Logic-immo.com</T><A>https://www.logic-immo.com/</A><L>fr</L><F>HTML</F></X></ITEM>
    <ITEM><X><T>leboncoin</T><A>https://www.leboncoin.fr/annonces/offres</A><L>fr</L><F>HTML</F></X></ITEM>
  </BLIST></ITEM>
  <ITEM><BLIST><TITLE>Agencies</TITLE>
    <ITEM><BLIST><TITLE>France</TITLE>
      <ITEM><X><T>FNAIM</T><A>https://www.fnaim.fr</A><L>fr</L><F>HTML</F></X></ITEM>
      <ITEM><X><T>SNPI</T><A>https://www.snpi.com/</A><L>fr</L><F>HTML</F></X></ITEM>
      <ITEM><X><T>Century 21</T><A>https://www.century21france.fr/</A><L>fr</L><F>HTML</F></X></ITEM>
      <ITEM><X><T>FONCIA</T><A>https://www.foncia.fr/</A><L>fr</L><F>HTML</F></X></ITEM>
      <ITEM><X><T>Batigère</T><A>https://www.batigere.fr</A><L>fr</L><F>HTML</F></X></ITEM>
      <ITEM><X><T>ORPI</T><A>https://www.orpi.com/</A><L>fr</L><F>HTML</F></X></ITEM>
      <ITEM><X><T>Nexity</T><A>https://www.nexity.fr</A><L>fr</L><F>HTML</F></X></ITEM>
      <ITEM><X><T>Guy Hoquet</T><A>https://www.guy-hoquet.com/</A><L>fr</L><F>HTML</F></X></ITEM>
    </BLIST></ITEM>
    <ITEM><BLIST><TITLE>Lorraine</TITLE>
      <ITEM><X><T>FNAIM Lorraine</T><A>http://www.fnaimlorraine.com/</A><L>fr</L><F>HTML</F></X></ITEM>
      <ITEM><X><T>Novadimm</T><A>http://www.novadimm.com/</A><L>fr</L><F>HTML</F></X></ITEM>
      <ITEM><X><T>Claude Rizzon</T><A>https://www.rizzon.com/</A><L>fr</L><F>HTML</F></X></ITEM>
      <ITEM><X><T>Liberty Home</T><A>https://www.libertyhome.fr/</A><L>fr</L><F>HTML</F></X></ITEM>
      <ITEM><BLIST><TITLE>Meurthe-et-Moselle</TITLE>
        <ITEM><X><T>Bonnabelle</T><A>http://www.bonnabelle.fr/</A><L>fr</L><F>HTML</F></X></ITEM>
        <ITEM><X><T>Cabinet Devaux</T><A>http://www.cabinetdevaux.com/</A><L>fr</L><F>HTML</F></X></ITEM>
        <ITEM><X><T>Alpha Conseil</T><A>https://www.alphaconseilimmobilier.com/</A><L>fr</L><F>HTML</F></X></ITEM>
        <ITEM><X><T>Joël Pierre Immobilier</T><A>https://www.century21-joelpierre-nancy.com/</A><L>fr</L><F>HTML</F></X></ITEM>
        <ITEM><X><T>Crepol</T><A>https://www.crepol.com/</A><L>fr</L><F>HTML</F></X></ITEM>
        <ITEM><X><T>Immobilier Conseil Debever</T><A>http://www.immoconseil-debever.com</A><L>fr</L><F>HTML</F></X></ITEM>
        <ITEM><X><T>Société Lorraine d'Habitat</T><A>https://www.lorraine-habitat.fr/</A><L>fr</L><F>HTML</F></X></ITEM>
      </BLIST></ITEM>
      <ITEM><BLIST><TITLE>Moselle</TITLE>
        <ITEM><X><T>Norman Parker</T><A>http://www.normanparker57.com</A><L>fr</L><F>HTML</F></X></ITEM>
      </BLIST></ITEM>
    <ITEM><BLIST><TITLE>Rhône-Alpes</TITLE>
      <ITEM><BLIST><TITLE>Drôme</TITLE>
        <ITEM><X><T>Les 2 Rives</T><A>https://www.les-2rives.fr/index.php</A><L>fr</L><F>HTML</F></X></ITEM>
      </BLIST></ITEM>
    </BLIST></ITEM>
    </BLIST></ITEM>
  </BLIST></ITEM>
</BLIST>
</CONTENT>
</PAGE>

=== lmazure/Homepage/bouffe/0133.xml
<?xml version="1.0"?>
<?xml-stylesheet type="text/xsl" href="../css/strict.xsl"?>
<PAGE xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../css/schema.xsd">
<TITLE>Spätzles</TITLE>
<PATH>bouffe/0133.xml</PATH>
<DATE><YEAR>2010</YEAR><MONTH>10</MONTH><DAY>25</DAY></DATE>
<CONTENT>
<SLIST>
  <ITEM>préparation : 15 min</ITEM>
  <ITEM>cuisson : 20 min</ITEM>
</SLIST>
<LINE/>
<BLIST><TITLE>Pour 6 personnes</TITLE>
  <ITEM>600g de farine</ITEM>
  <ITEM>60g de semoule de blé tendre</ITEM>
  <ITEM>6 œufs</ITEM>
  <ITEM>35g de sel fin</ITEM>
  <ITEM>gros sel</ITEM>
  <ITEM>beurre</ITEM>
</BLIST>
<LINE/>
<BLIST>
  <ITEM>Mélanger la farine, la semoule, les œufs, 22,5 cl d'eau et le sel. Passer cette masse à travers la grille à trous de votre moulin à légumes, dans une grande casserole d'eau bouillante salée.</ITEM>
  <ITEM>Quand les spätzles remontent, laisser cuire encore quelques minutes puis les refroidir dans de l'eau glacée. Bien les égoutter et, au moment de servir, les faire sauter au beurre.</ITEM>
</BLIST>
<I><U>source :</U> "Recettes gourmandes de nos terroirs - Alsace " - page 59</I>
</CONTENT>
</PAGE>

=== lmazure/Homepage/quality/scatter.xml
<?xml version="1.0"?>
<?xml-stylesheet type="text/xsl" href="../css/strict.xsl"?>
<PAGE xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../css/schema.xsd">
<TITLE>Scatter Diagram</TITLE>
<PATH>quality/scatter.xml</PATH>
<DATE><YEAR>2010</YEAR><MONTH>10</MONTH><DAY>25</DAY></DATE>
<CONTENT>
<BLIST><TITLE>Links</TITLE>
<ITEM><X><T>Wikipedia</T><A>https://en.wikipedia.org/wiki/Scatter_diagram</A><L>en</L><F>HTML</F></X></ITEM>
</BLIST>
</CONTENT>
</PAGE>

=== lmazure/Homepage/bouffe/0128.xml
<?xml version="1.0"?>
<?xml-stylesheet type="text/xsl" href="../css/strict.xsl"?>
<PAGE xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../css/schema.xsd" xml:lang="fr">
<TITLE>Sauce tomate classique et une variante</TITLE>
<PATH>bouffe/0128.xml</PATH>
<DATE><YEAR>2010</YEAR><MONTH>10</MONTH><DAY>25</DAY></DATE>
<CONTENT>
<SLIST>
  <ITEM>Préparation et cuisson : 40 mn environ</ITEM>
</SLIST>
<LINE/>
<BLIST><TITLE>Pour 5 à 6 personnes :</TITLE>
  <ITEM>500 g de tomates</ITEM>
  <ITEM>2 cuillerées à soupe de concentré de tomates</ITEM>
  <ITEM>20cl de vin blanc sec</ITEM>
  <ITEM>1 gros oignon</ITEM>
  <ITEM>2 gousses d'ail</ITEM>
  <ITEM>1 gros bouquet garni</ITEM>
  <ITEM>1 cuillerée à soupe d'huile d'olive</ITEM>
  <ITEM>1/2 cuillerée à café de sucre en poudre</ITEM>
  <ITEM>sel et poivre</ITEM>
</BLIST>
<LINE/>
<BLIST>
  <ITEM>Portez une casserole d'eau à ébullition ; plonger-y les tomates pendant 5 à 6 secondes, puis égouttez-les, pelez-les, retirez-en le cœur dur et hachez-les grossièrement ; pelez et hachez l'oignon ; épluchez et écrasez l'ail.</ITEM>
  <ITEM>Faites chauffez l'huile dans une casserole à fond épais ; mettez-y l'oignon ; faites-le blondir 2 ou 3 minutes en remuant, ajoutez les tomates et l'ail ; mélangez bien ; ajoutez ensuite le concentré de tomates et le vin blanc ; mélangez ; ajoutez enfin le sucre en poudre et le bouquet garni ; salez et poivrez ; portez à ébullition, puis faites cuire 25 minutes à petits frémissements en remuant de temps en temps.</ITEM>
  <ITEM>Quand la sauce est cuite, retirez-en le bouquet garni ; rectifiez l'assaisonnement ; servez la sauce telle quelle ou passez-la au mixer et faites-la réchauffer sur feu doux.</ITEM>
  <ITEM>Pour servir avec du poisson, vous pouvez ajouter à cette sauce 4 filets d'anchois réduits en purée et 1 cuillerée de câpres.</ITEM>
  <ITEM>En hiver, vous pouvez supprimer les tomates fraîches et utiliser 5 cuillerées à soupe de concentré de tomates.</ITEM>
</BLIST>
<I><U>source :</U> "Mon Bouquin de Cuisine" par Françoise Burgaud - page 1104</I>
</CONTENT>
</PAGE>

=== lmazure/Homepage/links/theater.xml
<?xml version="1.0"?>
<?xml-stylesheet type="text/xsl" href="../css/strict.xsl"?>
<PAGE xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../css/schema.xsd">
<TITLE>Theater</TITLE>
<PATH>links/theater.xml</PATH>
<DATE><YEAR>2010</YEAR><MONTH>10</MONTH><DAY>25</DAY></DATE>
<CONTENT>

<X><T>Th&#233;&#226;tre du Palais Royal</T><A>http://www.theatrepalaisroyal.com/</A><L>fr</L><F>HTML</F></X><BR/>

<LINE/>

<BLIST><TITLE><U><B>articles</B></U></TITLE>
  <ITEM><ARTICLE><X><T>Keith Barry: Brain magic</T><A>http://www.youtube.com/watch?v=GigYWy2UmOY</A><L>en</L><F>Flash Video</F><DURATION><MINUTE>19</MINUTE><SECOND>50</SECOND></DURATION></X><X><T>Keith Barry: Brain magic</T><A>http://www.ted.com/index.php/talks/keith_barry_does_brain_magic.html</A><L>en</L><F>Flash Video</F><DURATION><MINUTE>19</MINUTE><SECOND>49</SECOND></DURATION></X><AUTHOR>Keith Barry</AUTHOR><DATE><YEAR>2004</YEAR><MONTH>2</MONTH></DATE><COMMENT>Some illusionist tricks.</COMMENT></ARTICLE></ITEM>
  <ITEM><ARTICLE><X><T>Eric Mead: The magic of the placebo</T><A>http://www.youtube.com/watch?v=Cb_6PPBJJB8</A><L>en</L><F>Flash Video</F><DURATION><MINUTE>9</MINUTE><SECOND>6</SECOND></DURATION></X><X><T>Eric Mead: The magic of the placebo</T><A>http://www.ted.com/talks/eric_mead_the_magic_of_the_placebo.html</A><L>en</L><F>Flash Video</F><DURATION><MINUTE>9</MINUTE><SECOND>6</SECOND></DURATION></X><AUTHOR>Eric Mead</AUTHOR><DATE><YEAR>2009</YEAR><MONTH>10</MONTH></DATE><COMMENT>The needle through the arm trick.</COMMENT></ARTICLE></ITEM>
  <ITEM><ARTICLE><X><T>needle thru arm explanation</T><A>http://www.youtube.com/watch?v=fwarxzLzBXI</A><L>en</L><F>Flash Video</F><DURATION><MINUTE>6</MINUTE><SECOND>4</SECOND></DURATION></X><AUTHOR>Russ Kaine</AUTHOR><DATE><YEAR>2007</YEAR><MONTH>6</MONTH><DAY>28</DAY></DATE><COMMENT>A very good explanation of the previous trick.</COMMENT></ARTICLE></ITEM>
</BLIST>

</CONTENT>
</PAGE>
