=== lmazure/Homepage/css/schema.xsd
<?xml version="1.0" encoding="ISO-8859-1"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

<!-- Import xml: namespace -->
<xs:import namespace="http://www.w3.org/XML/1998/namespace" schemaLocation="xml.xsd"/>

<!-- definition of the types -->
<xs:simpleType name="noZeroInteger">
  <xs:restriction base="xs:integer">
    <xs:pattern value="[1-9]*[0-9]"/>
  </xs:restriction>
</xs:simpleType>

<xs:complexType name="person">
  <xs:sequence>
    <xs:element name="NAMEPREFIX" type="xs:string" minOccurs="0" maxOccurs="1"/>
    <xs:element name="FIRSTNAME" type="xs:string" minOccurs="0" maxOccurs="1"/>
    <xs:element name="MIDDLENAME" type="xs:string" minOccurs="0" maxOccurs="1"/>
    <xs:element name="LASTNAME" type="xs:string" minOccurs="0" maxOccurs="1"/>
    <xs:element name="NAMESUFFIX" type="xs:string" minOccurs="0" maxOccurs="1"/>
    <xs:element name="GIVENNAME" type="xs:string" minOccurs="0" maxOccurs="1"/>
  </xs:sequence>
</xs:complexType>

<xs:complexType name="fullDate">
  <xs:sequence>
    <xs:element name="YEAR" type="xs:integer"/>
    <xs:element name="MONTH">
      <xs:simpleType>
        <xs:restriction base="noZeroInteger">
          <xs:maxInclusive value="12"/>
        </xs:restriction>
      </xs:simpleType>
    </xs:element>
    <xs:element name="DAY">
      <xs:simpleType>
        <xs:restriction base="noZeroInteger">
          <xs:maxInclusive value="31"/>
        </xs:restriction>
      </xs:simpleType>
    </xs:element>
  </xs:sequence>
</xs:complexType>

<xs:complexType name="partialDate">
  <xs:sequence>
    <xs:element name="YEAR" type="xs:integer"/>
    <xs:element name="MONTH" minOccurs="0" maxOccurs="1">
      <xs:simpleType>
        <xs:restriction base="noZeroInteger">
          <xs:maxInclusive value="12"/>
        </xs:restriction>
      </xs:simpleType>
    </xs:element>
    <xs:element name="DAY" minOccurs="0" maxOccurs="1">
      <xs:simpleType>
        <xs:restriction base="noZeroInteger">
          <xs:maxInclusive value="31"/>
        </xs:restriction>
      </xs:simpleType>
    </xs:element>
  </xs:sequence>
</xs:complexType>

<xs:complexType name="duration">
  <xs:sequence>
    <xs:element name="HOUR" minOccurs="0" maxOccurs="1">
      <xs:simpleType>
        <xs:restriction base="noZeroInteger">
          <xs:minInclusive value="1"/>
        </xs:restriction>
      </xs:simpleType>
    </xs:element>
    <xs:element name="MINUTE" minOccurs="0" maxOccurs="1">
      <xs:simpleType>
        <xs:restriction base="noZeroInteger">
          <xs:maxInclusive value="59"/>
        </xs:restriction>
      </xs:simpleType>
    </xs:element>
    <xs:element name="SECOND" minOccurs="1" maxOccurs="1">
      <xs:simpleType>
        <xs:restriction base="noZeroInteger">
          <xs:maxInclusive value="59"/>
        </xs:restriction>
      </xs:simpleType>
    </xs:element>
  </xs:sequence>
</xs:complexType>

<xs:complexType name="content" mixed="true">
  <xs:choice minOccurs="0" maxOccurs="unbounded">
    <xs:element ref="BLIST"/>
    <xs:element ref="SLIST"/>
    <xs:element ref="NLIST"/>
    <xs:element ref="CLIST"/>
    <xs:element ref="LLIST"/>
    <xs:element ref="DEFINITIONTABLE"/>
    <xs:element ref="DEFINITION2TABLE"/>
    <xs:element ref="TABLE"/>
    <xs:element ref="MATH"/>
    <xs:element ref="MERMAID"/>
    <xs:element ref="TEXTBLOCK"/>
    <xs:element ref="CODEMENU"/>
    <xs:element ref="CODESAMPLE"/>
    <xs:element ref="CODEROUTINE"/>
    <xs:element ref="CODEFILENAME"/>
    <xs:element name="DATE" type="partialDate"/>
    <xs:element name="DURATION" type="duration"/>
    <xs:element ref="LINE"/>
    <xs:element ref="ANCHOR"/>
    <xs:element ref="U"/>
    <xs:element ref="B"/>
    <xs:element ref="I"/>
    <xs:element ref="SMALL"/>
    <xs:element ref="SUB"/>
    <xs:element ref="SUP"/>
    <xs:element ref="X"/>
    <xs:element ref="ARTICLE"/>
    <xs:element ref="BR"/>
    <xs:element ref="KEY"/>
    <xs:element ref="MODIFIERKEY"/>
    <xs:element ref="IMAGE"/>
    <xs:element name="AUTHOR" type="person"/>
    <xs:element name="KEYWORD"/>
  </xs:choice>
  <xs:attribute ref="xml:lang" use="optional"/>
</xs:complexType>

<!-- definition of the tags -->

<xs:element name="PAGE">
  <xs:complexType>
    <xs:sequence>
      <xs:element name="TITLE" type="xs:string" minOccurs="1" maxOccurs="1"/>
      <xs:element name="PATH" type="xs:string" minOccurs="1" maxOccurs="1"/>
      <xs:element name="DATE" type="fullDate" minOccurs="1" maxOccurs="1"/>
      <xs:element ref="CONTENT" minOccurs="1" maxOccurs="1"/>
      <xs:element ref="X" minOccurs="0" maxOccurs="unbounded"/>
      <xs:element ref="SCRIPT" minOccurs="0" maxOccurs="1"/>
    </xs:sequence>
    <xs:attribute name="special">
     <xs:simpleType>
       <xs:restriction base="xs:string">
         <xs:pattern value="indexed"/>
       </xs:restriction>
      </xs:simpleType>
    </xs:attribute>
    <xs:attribute name="status">
     <xs:simpleType>
       <xs:restriction base="xs:string">
         <xs:pattern value="unmaintained"/>
       </xs:restriction>
      </xs:simpleType>
    </xs:attribute>
    <xs:attribute ref="xml:lang" use="required"/>
  </xs:complexType>
</xs:element>

<xs:element name="CONTENT" type="content"/>

<xs:complexType name="List">
  <xs:sequence>
    <xs:element name="TITLE" type="content" minOccurs="0" maxOccurs="1"/>
    <xs:element name="SUBTITLE" type="content" minOccurs="0" maxOccurs="1"/>
    <xs:element name="ITEM" type="content" minOccurs="1" maxOccurs="unbounded"/>
  </xs:sequence>
</xs:complexType>

<xs:element name="BLIST" type="List"/>
<xs:element name="SLIST" type="List"/>
<xs:element name="NLIST" type="List"/>
<xs:element name="CLIST" type="List"/>
<xs:element name="LLIST" type="List"/>

<xs:element name="U" type="content"/>

<xs:element name="B" type="content"/>

<xs:element name="I" type="content"/>

<xs:element name="SMALL" type="content"/>

<xs:element name="SUB" type="xs:string"/>

<xs:element name="SUP" type="xs:string"/>

<xs:element name="X">
  <xs:complexType>
    <xs:sequence>
      <xs:element name="T" minOccurs="1" maxOccurs="1">
        <xs:complexType mixed="true">
          <xs:choice minOccurs="0" maxOccurs="unbounded">
            <xs:element ref="CODEROUTINE"/>
            <xs:element ref="CODEFILENAME"/>
          </xs:choice>
        </xs:complexType>
      </xs:element>
      <xs:element name="ATTRIBUTE" minOccurs="0" maxOccurs="unbounded">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="ATTRIBUTENAME" type="xs:string"/>
            <xs:element name="ATTRIBUTEVALUE" type="xs:string"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element name="ST" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
      <xs:element name="A" type="xs:anyURI" minOccurs="1" maxOccurs="1"/>
      <xs:element name="L" minOccurs="1" maxOccurs="3">
        <xs:simpleType>
         <xs:restriction base="xs:string">
           <xs:pattern value="de|en|fr|ru"/>
         </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="F" minOccurs="1" maxOccurs="unbounded">
        <xs:simpleType>
         <xs:restriction base="xs:string">
           <xs:pattern value="Flash|Flash Video|HTML|MP3|MP4|PDF|PostScript|PowerPoint|RealMedia|txt|Windows Media Player|Word"/>
         </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="FEED" minOccurs="0" maxOccurs="1">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="A" type="xs:anyURI"/>
            <xs:element name="F">
              <xs:simpleType>
               <xs:restriction base="xs:string">
                 <xs:pattern value="RSS|RSS2|Atom"/>
               </xs:restriction>
              </xs:simpleType>
            </xs:element>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element name="DURATION" type="duration" minOccurs="0" maxOccurs="1"/>
      <xs:element name="DATE" type="partialDate" minOccurs="0" maxOccurs="1"/>
    </xs:sequence>
    <xs:attribute name="status">
     <xs:simpleType>
       <xs:restriction base="xs:string">
         <xs:pattern value="obsolete|dead|zombie|removed"/>
       </xs:restriction>
      </xs:simpleType>
    </xs:attribute>
    <xs:attribute name="protection">
     <xs:simpleType>
       <xs:restriction base="xs:string">
         <xs:pattern value="payed_registration|free_registration"/>
       </xs:restriction>
      </xs:simpleType>
    </xs:attribute>
    <xs:attribute name="quality">
     <xs:simpleType>
       <xs:restriction base="xs:integer">
          <xs:minInclusive value="-2"/>
          <xs:maxInclusive value="2"/>
       </xs:restriction>
      </xs:simpleType>
    </xs:attribute>
  </xs:complexType>
</xs:element>

<xs:element name="ARTICLE">
  <xs:complexType>
    <xs:sequence>
      <xs:element ref="X" minOccurs="1" maxOccurs="unbounded"/>
      <xs:element name="AUTHOR" minOccurs="0" maxOccurs="unbounded" type="person"/>
      <xs:element name="DATE" type="partialDate" minOccurs="0" maxOccurs="1"/>
      <xs:element name="COMMENT" type="content" minOccurs="1" maxOccurs="1"/>
    </xs:sequence>
    <xs:attribute name="predecessor" type="xs:string"/>
  </xs:complexType>
</xs:element>

<xs:element name="KEYWORD">
  <xs:complexType>
    <xs:sequence>
      <xs:element name="KEYID" type="xs:string" minOccurs="1" maxOccurs="1"/>
      <xs:element name="KEYEDTEXT" type="content" minOccurs="1" maxOccurs="1"/>
    </xs:sequence>
  </xs:complexType>
</xs:element>

<xs:element name="LINE"/>

<xs:element name="ANCHOR" type="xs:string"/>

<xs:element name="DEFINITIONTABLE">
  <xs:complexType>
    <xs:sequence>
      <xs:element name="ROW" minOccurs="1" maxOccurs="unbounded">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="TERM" type="content"/>
            <xs:element name="DESC" type="content"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
</xs:element>

<xs:element name="DEFINITION2TABLE">
  <xs:complexType>
    <xs:sequence>
      <xs:element name="ROW" minOccurs="1" maxOccurs="unbounded">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="TERM1" type="content"/>
            <xs:element name="TERM2" type="content"/>
            <xs:element name="DESC" type="content"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
</xs:element>

<xs:element name="TABLE">
  <xs:complexType>
    <xs:sequence>
      <xs:element name="ROW" minOccurs="1" maxOccurs="unbounded">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="CELL" minOccurs="1" maxOccurs="unbounded">
              <xs:complexType>
                <xs:complexContent>
                  <xs:extension base="content">
                    <xs:attribute name="width" type="xs:nonNegativeInteger"/>
                    <xs:attribute name="height" type="xs:nonNegativeInteger"/>
                  </xs:extension>
                </xs:complexContent>
              </xs:complexType>
            </xs:element>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
</xs:element>

<xs:element name="TEXTBLOCK" type="content"/>

<xs:element name="MATH" type="xs:string"/>

<xs:element name="MERMAID" type="xs:string"/>

<xs:element name="CODEMENU">
  <xs:complexType mixed="true">
    <xs:sequence>
      <xs:element ref="CODEMENU" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>
</xs:element>

<xs:element name="CODESAMPLE">
  <xs:complexType mixed="true">
    <xs:sequence maxOccurs="unbounded">
      <xs:element ref="PROMPT" minOccurs="0"/>
      <xs:element ref="TAB" minOccurs="0" maxOccurs="unbounded"/>
      <xs:element ref="BR" minOccurs="0" maxOccurs="1"/>
      <xs:element name="I" minOccurs="0" maxOccurs="unbounded" type="xs:string"/>
      <xs:element name="B" minOccurs="0" maxOccurs="unbounded" type="xs:string"/>
      <xs:element name="U" minOccurs="0" maxOccurs="unbounded" type="xs:string"/>
      <xs:element ref="X" minOccurs="0" maxOccurs="unbounded"/>
      <xs:element ref="CODEFILENAME" minOccurs="0" maxOccurs="unbounded"/>
    </xs:sequence>
  <xs:attribute  name="language" use="optional"/>
  </xs:complexType>
</xs:element>

<xs:element name="CODEROUTINE">
  <xs:complexType mixed="true">
    <xs:sequence maxOccurs="unbounded">
      <xs:element name="I" minOccurs="0" maxOccurs="unbounded" type="xs:string"/>
      <xs:element ref="X" minOccurs="0" maxOccurs="unbounded"/>
      <xs:element ref="CODEFILENAME" minOccurs="0" maxOccurs="unbounded"/>
      <xs:element ref="TAB" minOccurs="0" maxOccurs="unbounded"/>
    </xs:sequence>
  </xs:complexType>
</xs:element>

<xs:element name="CODEFILENAME">
  <xs:complexType mixed="true">
    <xs:sequence minOccurs="0" maxOccurs="1">
      <xs:element ref="X" minOccurs="0" maxOccurs="1"/>
    </xs:sequence>
  </xs:complexType>
</xs:element>

<xs:element name="DATE" type="fullDate"/>

<xs:element name="PROMPT"/>

<xs:element name="TAB"/>

<xs:element name="BR"/>

<xs:element name="KEY">
  <xs:complexType>
    <xs:attribute name="id" type="xs:string"/>
  </xs:complexType>
</xs:element>

<xs:element name="MODIFIERKEY">
  <xs:complexType>
    <xs:attribute name="id" type="xs:string"/>
  </xs:complexType>
</xs:element>

<xs:element name="SCRIPT" type="xs:string"/>

<xs:element name="IMAGE" type="xs:anyURI"/>

</xs:schema>

=== lmazure/Homepage/bouffe/0119.xml
<?xml version="1.0"?>
<?xml-stylesheet type="text/xsl" href="../css/strict.xsl"?>
<PAGE xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../css/schema.xsd" xml:lang="fr">
<TITLE>Cake aux lardons, poulet et olives</TITLE>
<PATH>bouffe/0119.xml</PATH>
<DATE><YEAR>2010</YEAR><MONTH>10</MONTH><DAY>25</DAY></DATE>
<CONTENT>
<SLIST>
  <ITEM>préparation : 20 min</ITEM>
  <ITEM>cuisson : 45 min</ITEM>
</SLIST>
<LINE/>
<BLIST><TITLE>Pour 8 personnes</TITLE>
  <ITEM>100g de blanc de poulet cuit</ITEM>
  <ITEM>100g de lardons fumés</ITEM>
  <ITEM>100g de champignons de Paris</ITEM>
  <ITEM>20 olives noires dénoyautées</ITEM>
  <ITEM>1 cuil. à soupe de persil haché</ITEM>
  <ITEM>225g de farine + 10g</ITEM>
  <ITEM>100g de beurre + 15g</ITEM>
  <ITEM>4 œufs</ITEM>
  <ITEM>1/2 paquet de levure chimique</ITEM>
  <ITEM>10cl de vin blanc sec</ITEM>
  <ITEM>1 cuil. à soupe d’huile d’arachide</ITEM>
  <ITEM>1/2 cuil. à café de sel</ITEM>
</BLIST>
<LINE/>
<BLIST>
  <ITEM>Allumez le four th. 6-7 (200°C). Beurrez et farinez un moule à cake. Coupez les olives en morceaux. Émincez le poulet en lamelles. Faites fondre le beurre.</ITEM>
  <ITEM>Dorez les lardons dans une cuillerée d’huile à la poêle. Réservez. Nettoyez et émincez les champignons. Faites-les revenir à la poêle avec une pincée de sel jusqu’à ce qu’ils rendent leur eau. Versez en passoire.</ITEM>
  <ITEM>Dans un saladier, mêlez la farine, le sel et la levure. Creusez au centre et cassez-y les œufs. Mélangez à la cuillère en bois en incorporant peu à peu la farine, tout en versant progressivement le beurre fondu puis le vin. Ajoutez persil, olives, poulet, lardons et champignons à la pâte, puis versez-la dans le moule.</ITEM>
  <ITEM>Cuisez 45 min. Vérifiez en enfonçant une brochette au centre, elle doit ressortir sèche. Laissez tiédir 5 min avant de démouler et laissez refroidir sur une grille.</ITEM>
</BLIST>
<I><U>source :</U> Cuisine Actuelle - Hors-Série juin-juillet 2004 - page 42</I>
</CONTENT>
</PAGE>

=== lmazure/Homepage/notes/tfs.xml
<?xml version="1.0"?>
<?xml-stylesheet type="text/xsl" href="../css/strict.xsl"?>
<PAGE xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../css/schema.xsd">
<TITLE>TFS</TITLE>
<PATH>notes/tfs.xml</PATH>
<DATE><YEAR>2015</YEAR><MONTH>1</MONTH><DAY>6</DAY></DATE>
<CONTENT>

<CODEROUTINE><PROMPT/>tf="/cygdrive/c/Program Files (x86)/Microsoft Visual Studio 11.0/Common7/IDE/TF.exe"</CODEROUTINE><BR/>
<BR/>

create a workspace <I>foobar</I><BR/>
<CODEROUTINE><PROMPT/>cd "$tfsdir"</CODEROUTINE><BR/>
<CODEROUTINE><PROMPT/>mkdir <I>foobar</I></CODEROUTINE><BR/>
<CODEROUTINE><PROMPT/>cd "<I>foobar</I></CODEROUTINE><BR/>
<CODEROUTINE><PROMPT/>"$tf" workspace /new <I>foobar</I> /collection:http://alm.eurofins.local/tfs/eurofinscollection</CODEROUTINE><BR/>
<CODEROUTINE><PROMPT/>"$tf" get "eCommerce/EOL/Trunk" /recursive</CODEROUTINE><BR/>
<BR/>

delete a workspace <I>foobar</I><BR/>
<CODEROUTINE><PROMPT/>"$tf" workspace /delete <I>foobar</I></CODEROUTINE><BR/>
<CODEROUTINE><PROMPT/>cd "$tfsdir"</CODEROUTINE><BR/>
<CODEROUTINE><PROMPT/>rm -fr <I>foobar</I></CODEROUTINE><BR/>
<BR/>

</CONTENT>
<X><T>links</T><A>../links/coding.html#tfs</A><L>en</L><F>HTML</F></X>
</PAGE>

=== lmazure/Homepage/bouffe/0144.xml
<?xml version="1.0"?>
<?xml-stylesheet type="text/xsl" href="../css/strict.xsl"?>
<PAGE xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../css/schema.xsd">
<TITLE>Chou blanc à la crème</TITLE>
<PATH>bouffe/0144.xml</PATH>
<DATE><YEAR>2010</YEAR><MONTH>10</MONTH><DAY>25</DAY></DATE>
<CONTENT>
<SLIST>
  <ITEM>Préparation : 10 mn</ITEM>
  <ITEM>Cuisson en trois fois : 1h 15 environ</ITEM>
</SLIST>
<LINE/>
<BLIST><TITLE>Pour 4 personnes :</TITLE>
  <ITEM>1 petit chou blanc</ITEM>
  <ITEM>20g de beurre</ITEM>
  <ITEM>1 dl 1/2 de crème fraîche épaisse</ITEM>
  <ITEM>gros sel</ITEM>
  <ITEM>sel et poivre</ITEM>
</BLIST>
<LINE/>
<BLIST>
  <ITEM>Faites bouillir un faitout d'eau ; pendant ce temps, nettoyer le chou, coupez-le en huit, débarrassez le de la partie dure du cœur ; jetez les morceaux dans l'eau bouillante et laissez-le blanchir 5 minutes, puis égouttez-le, rafraîchissez-le sous l'eau froide, égouttez-le à nouveau.</ITEM>
  <ITEM>Jetez l'eau de blanchiment et faites bouillir à nouveau de l'eau ; ajoutez une poignée de gros sel, puis les morceaux de chou ; laissez cuire 35 minutes environ, puis égouttez à fond ; faites chauffer le four à 250°C.</ITEM>
  <ITEM>Beurrez un plat à gratin juste assez grand pour contenir les morceaux de chou, disposez-les dans le plat, nappez de crème fraîche, salez, poivrez, couvrez d'un papier aluminium, enfournez et laissez chauffer 15 minutes environ.</ITEM>
  <ITEM>Servez ce chou très chaud, par exemple avec des côtes de veau ou un poisson blanc poché.</ITEM>
  <ITEM>Vous pouvez remplacer la cuisson au four par la cuisson en cocotte ; vous pouvez aussi remplacer la crème par une béchamel légère, parsemer de gruyère râpé et de noisettes de beurre et faire gratiner.</ITEM>
</BLIST>
<I><U>source :</U> "Mon Bouquin de Cuisine" par Françoise Burgaud - page 343</I>
</CONTENT>
</PAGE>

=== lmazure/Homepage/bouffe/0157.xml
<?xml version="1.0"?>
<?xml-stylesheet type="text/xsl" href="../css/strict.xsl"?>
<PAGE xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../css/schema.xsd">
<TITLE>petits g&#xE2;teaux aux carottes (Inde)</TITLE>
<PATH>bouffe/0157.xml</PATH>
<DATE><YEAR>2010</YEAR><MONTH>10</MONTH><DAY>25</DAY></DATE>
<CONTENT>

<SLIST>
<ITEM>Pr&#xE9;paration : 15 min</ITEM>
<ITEM>Cuisson : 30 &#xE0; 40 min</ITEM>
</SLIST>

<LINE/>

<BLIST><TITLE>Ingr&#xE9;dients :</TITLE>
<ITEM>500g de carottes</ITEM>
<ITEM>50g de raisins secs</ITEM>
<ITEM>40g de beurre</ITEM>
<ITEM>20g d'amandes effil&#xE9;es</ITEM>
<ITEM>3 gousses de cardamone</ITEM>
<ITEM>1 pinc&#xE9;e de 4 &#xE9;pices</ITEM>
<ITEM>90cl de lait</ITEM>
<ITEM>125g de sucre</ITEM>
<ITEM>20g de pistache</ITEM>
</BLIST>

<LINE/>

<BLIST>
<ITEM>&#xC9;plucher, laver et r&#xE2;per les carottes.</ITEM>
<ITEM>Faire chauffer le beurre dans une po&#xEA;le, y d&#xE9;poser les carottes et ajouter le lait et le sucre.</ITEM>
<ITEM>Faire cuire pendant 20 &#xE0; 30 min jusqu'&#xE0; ce que les carottes aient absorb&#xE9; tout le lait.</ITEM>
<ITEM>Ajouter les raisins secs puis faire cuire &#xE0; feu moyen pendant 10 min en remuant r&#xE9;guli&#xE8;rement avec une cuill&#xE8;re en bois.</ITEM>
<ITEM>Ouvrir les gousses de cardamome, r&#xE9;cup&#xE9;rer les graines et les &#xE9;craser ; les incorporer hors du feu avec les autres &#xE9;pices.</ITEM>
<ITEM>Laisser refroidir et d&#xE9;couper la p&#xE2;te en carr&#xE9;s ou en losanges.</ITEM>
<ITEM>D&#xE9;corer avec les amandes effil&#xE9;es ou les pistaches et servir ti&#xE8;de ou froid.</ITEM>
</BLIST>

<I><U>source :</U> "Carottes, je vous aime..." par B&#xE9;atrice Vigot-Lagandr&#xE9; - page 63</I>

</CONTENT>
</PAGE>
